-- ============================================================================
-- Migration: Seed Products Dictionary
-- Description: Inserts a curated list of 200 popular cooking ingredients
--              and pantry staples ordered roughly by usage frequency.
-- Notes: Uses ON CONFLICT DO NOTHING to keep the migration idempotent.
-- ============================================================================

insert into products (name)
values
  ('Chicken Breast'),
  ('Chicken Thigh'),
  ('Chicken Drumstick'),
  ('Turkey Breast'),
  ('Ground Beef'),
  ('Beef Sirloin'),
  ('Beef Chuck'),
  ('Pork Loin'),
  ('Pork Tenderloin'),
  ('Ground Turkey'),
  ('Salmon Fillet'),
  ('Tuna Steak'),
  ('Cod Fillet'),
  ('Shrimp'),
  ('Tilapia Fillet'),
  ('Eggs'),
  ('Mozzarella Cheese'),
  ('Cheddar Cheese'),
  ('Parmesan Cheese'),
  ('Greek Yogurt'),
  ('Whole Milk'),
  ('Heavy Cream'),
  ('Butter'),
  ('Sour Cream'),
  ('Cottage Cheese'),
  ('Ricotta Cheese'),
  ('Cream Cheese'),
  ('Bacon'),
  ('Ham'),
  ('Prosciutto'),
  ('Ground Pork'),
  ('Lamb Chops'),
  ('Duck Breast'),
  ('Tofu'),
  ('Tempeh'),
  ('Seitan'),
  ('Black Beans'),
  ('Chickpeas'),
  ('Lentils'),
  ('Kidney Beans'),
  ('Broccoli'),
  ('Cauliflower'),
  ('Spinach'),
  ('Kale'),
  ('Romaine Lettuce'),
  ('Arugula'),
  ('Mixed Greens'),
  ('Cabbage'),
  ('Carrots'),
  ('Celery'),
  ('Cucumbers'),
  ('Zucchini'),
  ('Eggplant'),
  ('Bell Pepper Red'),
  ('Bell Pepper Green'),
  ('Bell Pepper Yellow'),
  ('Bell Pepper Orange'),
  ('Tomatoes'),
  ('Cherry Tomatoes'),
  ('Onions Yellow'),
  ('Onions Red'),
  ('Onions White'),
  ('Garlic'),
  ('Shallots'),
  ('Leeks'),
  ('Green Onions'),
  ('Potatoes Russet'),
  ('Potatoes Yukon Gold'),
  ('Sweet Potatoes'),
  ('Mushrooms Button'),
  ('Mushrooms Cremini'),
  ('Mushrooms Portobello'),
  ('Asparagus'),
  ('Brussels Sprouts'),
  ('Green Beans'),
  ('Peas'),
  ('Corn Kernels'),
  ('Artichoke Hearts'),
  ('Beets'),
  ('Radishes'),
  ('Apples'),
  ('Bananas'),
  ('Strawberries'),
  ('Blueberries'),
  ('Raspberries'),
  ('Blackberries'),
  ('Pineapple'),
  ('Mango'),
  ('Peaches'),
  ('Plums'),
  ('Pears'),
  ('Oranges'),
  ('Lemons'),
  ('Limes'),
  ('Grapefruit'),
  ('Kiwis'),
  ('Grapes Red'),
  ('Grapes Green'),
  ('Watermelon'),
  ('Cantaloupe'),
  ('Honeydew'),
  ('Cherries'),
  ('Pomegranate Seeds'),
  ('Cranberries'),
  ('Apricots'),
  ('Dates'),
  ('Figs'),
  ('Coconut Flakes'),
  ('Raisins'),
  ('Dried Cranberries'),
  ('White Rice'),
  ('Brown Rice'),
  ('Jasmine Rice'),
  ('Basmati Rice'),
  ('Quinoa'),
  ('Couscous'),
  ('Bulgur'),
  ('Barley'),
  ('Farro'),
  ('Oats Rolled'),
  ('Oats Steel Cut'),
  ('Whole Wheat Flour'),
  ('All Purpose Flour'),
  ('Almond Flour'),
  ('Cornmeal'),
  ('Polenta'),
  ('Semolina'),
  ('Spaghetti'),
  ('Penne'),
  ('Fettuccine'),
  ('Linguine'),
  ('Lasagna Sheets'),
  ('Macaroni'),
  ('Egg Noodles'),
  ('Rice Noodles'),
  ('Soba Noodles'),
  ('Udon Noodles'),
  ('Tortillas Flour'),
  ('Tortillas Corn'),
  ('Pita Bread'),
  ('Baguette'),
  ('Sourdough Bread'),
  ('Whole Wheat Bread'),
  ('Breadcrumbs'),
  ('Panko Breadcrumbs'),
  ('Puff Pastry'),
  ('Phyllo Dough'),
  ('Pie Crust'),
  ('Almonds'),
  ('Walnuts'),
  ('Pecans'),
  ('Cashews'),
  ('Pistachios'),
  ('Hazelnuts'),
  ('Peanuts'),
  ('Sunflower Seeds'),
  ('Pumpkin Seeds'),
  ('Chia Seeds'),
  ('Flaxseeds'),
  ('Sesame Seeds'),
  ('Hemp Seeds'),
  ('Peanut Butter'),
  ('Almond Butter'),
  ('Tahini'),
  ('Extra Virgin Olive Oil'),
  ('Canola Oil'),
  ('Vegetable Oil'),
  ('Avocado Oil'),
  ('Coconut Oil'),
  ('Sesame Oil'),
  ('Balsamic Vinegar'),
  ('Red Wine Vinegar'),
  ('Apple Cider Vinegar'),
  ('White Vinegar'),
  ('Soy Sauce'),
  ('Tamari'),
  ('Worcestershire Sauce'),
  ('Fish Sauce'),
  ('Oyster Sauce'),
  ('Hot Sauce'),
  ('Barbecue Sauce'),
  ('Ketchup'),
  ('Mayonnaise'),
  ('Dijon Mustard'),
  ('Yellow Mustard'),
  ('Honey'),
  ('Maple Syrup'),
  ('Brown Sugar'),
  ('Granulated Sugar'),
  ('Powdered Sugar'),
  ('Molasses'),
  ('Baking Powder'),
  ('Baking Soda'),
  ('Cocoa Powder'),
  ('Vanilla Extract'),
  ('Cinnamon Ground'),
  ('Nutmeg Ground'),
  ('Paprika Smoked'),
  ('Cumin Ground'),
  ('Chili Powder')
on conflict (name) do nothing;


