name: Setup Playwright
description: Setup Playwright browsers and dependencies

runs:
  using: composite
  steps:
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
      shell: bash

